niche: "conspiracy theory"
affiliate_link: "https://your-affiliate-link.com"
donate_link: "https://ko-fi.com/yourname"

youtube:
  api_key: "AIzaSyAK4F7z8NM94mRoelIVOU8xUlNqcrpxeR4"
  channel_id: "UC-4wh1pS7IGl-RV2TWxXkQA"

tiktok:
  api_key: ""
  user_id: ""

instagram:
  username: ""
  password: ""

twitter:
  api_key: ""
  api_secret: ""
