name: Auto Poster

on:
  schedule:
    - cron: "0 12 * * *"   # runs daily at 12:00 UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2:
